### ISSUE TITLE
`microcloud init` can consume "at least 3 additional disks" by default but cannot reach to "for use by Ceph"

### ISSUE THREAD

**Issue by nobuto-m** [canonical/microcloud#74]
microcloud  0+git.445d39a

In the doc,

https://github.com/canonical/microcloud/blob/main/README.md?plain=1#L19
> A minimum of 3 systems and at least 3 additional disks for use by Ceph are required.

my understanding is one additional disk per system (3 additional disks **in total**) are expected as minimum.

Then, we run `microcloud init` as follows and by selecting the default suggested options, it can consume 3 additional disks before reaching to the Ceph stage and we end up with a situation where no disk is left for Ceph.

This first user journey could be improved by updating the description of questions in the init phase.

> Would you like to setup local storage? (yes/no) [**default=yes**]: 
> **Select exactly one disk from each cluster member:**

> Would you like to setup distributed storage? (yes/no) [**default=yes**]: 
> **Found no available disks**

```
$ uvt-kvm ssh microcloud-1 -- -t -- sudo microcloud init
Please choose the address MicroCloud will be listening on [default=192.168.122.230]: 
Scanning for eligible servers...
Press enter to end scanning for servers
 Found "microcloud-3" at "192.168.122.28"
 Found "microcloud-2" at "192.168.122.237"

Ending scan
Would you like to setup local storage? (yes/no) [default=yes]: 
Select exactly one disk from each cluster member:
Space to select; Enter to confirm; Esc to exit; Type to filter results.
Up/Down to move; Right to select all; Left to select none.
       +--------------+---------------+----------+------+-------------------------------------------------+
       |   LOCATION   |     MODEL     | CAPACITY | TYPE |                      PATH                       |
       +--------------+---------------+----------+------+-------------------------------------------------+
> [x]  | microcloud-1 | QEMU HARDDISK | 32.00GiB | scsi | /dev/disk/by-id/scsi-SATA_QEMU_HARDDISK_QM00001 |
  [x]  | microcloud-2 | QEMU HARDDISK | 32.00GiB | scsi | /dev/disk/by-id/scsi-SATA_QEMU_HARDDISK_QM00001 |
  [x]  | microcloud-3 | QEMU HARDDISK | 32.00GiB | scsi | /dev/disk/by-id/scsi-SATA_QEMU_HARDDISK_QM00001 |
       +--------------+---------------+----------+------+-------------------------------------------------+

Would you like to setup distributed storage? (yes/no) [default=yes]: 
Found no available disks
Retry selecting disks? (yes/no) [default=yes]: 
Found no available disks
Retry selecting disks? (yes/no) [default=yes]: no
Initializing a new cluster
 Local MicroCloud is ready
 Local MicroOVN is ready
 Local LXD is ready
 Local MicroCeph is ready
Awaiting cluster formation...
 Peer "microcloud-3" has joined the cluster
 Peer "microcloud-2" has joined the cluster
Cluster initialization is complete
Error: Pool not pending on any node (use --target <node> first)
```

**Comment by nobuto-m** [comment]
Besides, the distributed storage question isn't optional, is it?

> Would you like to setup distributed storage? (yes/no) [default=yes]: 

Because if we say "no" to this question, `microcloud init` fails with `Error: Pool not pending on any node (use --target <node> first)` I suppose. So giving an option there can confuse people.

**Comment by stgraber** [comment]
Yeah, I'd have expected `microcloud init` to not even ask the question in this case as there's no drives left.
It should just print `Skipping distributed storage due to insufficient disk availability` and indeed need to ensure that LXD behaves without distributed storage.

@masnax easy fix?

**Comment by masnax** [comment]
This was a regression from the last update. It’s fixed by #72

**Comment by stgraber** [comment]
Cool, I've got that one in my review pile for today.

**Comment by nobuto-m** [comment]
It doesn't error out with `Error: Pool not pending on any node (use --target <node> first)` now indeed after the improvement. But it didn't fix the original user story issue.

```
$ sudo microcloud init
Please choose the address MicroCloud will be listening on [default=192.168.122.227]: 
Please choose the subnet for MicroCloud (all/[subnet]) [default=192.168.122.0/24]: 
Scanning for eligible servers...

  Selected "mc-2" at "192.168.122.200"
  Selected "mc-3" at "192.168.122.235"

Would you like to setup local storage? (yes/no) [default=yes]: 
Select exactly one disk from each cluster member:

 Using "/dev/disk/by-id/scsi-SATA_QEMU_HARDDISK_QM00001" on "mc-1" for local storage pool
 Using "/dev/disk/by-id/scsi-SATA_QEMU_HARDDISK_QM00001" on "mc-2" for local storage pool
 Using "/dev/disk/by-id/scsi-SATA_QEMU_HARDDISK_QM00001" on "mc-3" for local storage pool

Would you like to setup distributed storage? (yes/no) [default=yes]: 
Found no available disks
Retry selecting disks? (yes/no) [default=yes]: 
Found no available disks
Retry selecting disks? (yes/no) [default=yes]: no
Initializing a new cluster
 Local MicroCloud is ready
 Local MicroOVN is ready
 Local LXD is ready
 Local MicroCeph is ready
Awaiting cluster formation...
 Peer "mc-2" has joined the cluster
 Peer "mc-3" has joined the cluster
Cluster initialization is complete
MicroCloud is ready
```

I suppose we should be clear on the local storage part that it's not distributed nor redundant but ephemeral. Just asking "do you need a local storage?" doesn't cover the implication.

Or we could flip the order of those two questions:
- Would you like to setup local storage?
- Would you like to setup distributed storage?

**Comment by stgraber** [comment]
It makes more sense to ask for local storage first as it's the most restrictive in the selection as it requires exactly one drive per system whereas for ceph, you just need a minimum of 3 drives across your entire cluster.

However I'd have preferred to see the `Would you like to setup distributed storage? (yes/no) [default=yes]:` be skipped entirely here and just replaced with a statement saying something like `Insufficient number of disks available to setup distributed storage, skipping at this time`.

Ceph can always be made available later by having users add disks to ceph until it can be brought up, same isn't true for local storage.

**Comment by nobuto-m** [comment]
You are absolutely correct from a technical standpoint.

I'm talking about more of a user story as per the subject.

> MicroCloud is the easiest way to get a fully highly available LXD cluster up and running.

> A minimum of 3 systems and at least 3 additional disks for use by Ceph are required.

So let's say an user would like to do a POC and prepared 3 servers with two drives (one for OS, and the other as unallocated). Then the user follows the `init` dialogue and selects suggested options. They may not get high availability or redundancy of their workload at the end.
